#!/bin/bash

source $HOME/.bash_colors

echo $CYAN"✔︎ Bootstrapping yadm"$STOP
cd "$HOME"

echo $CYAN"✔︎ Initializing submodules"$STOP
yadm submodule update --recursive --init

OS=$(uname -s)
RUBY=$(which ruby)
PKG=$(which pkg)
VIM=$(which vim)
NEOVIM=$(which neovim)
GIT=$(which git)
BREW=$(which brew)

if [ "$OS" = "Darwin" ]; then

    if ! command -v brew >/dev/null 2>&1; then
        echo $CYAN"✔︎ Installing homebrew"$STOP
        $RUBY -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    if [ -f "$HOME/.Brewfile" ]; then
        echo $CYAN"✔︎ Updating homebrew bundle"$STOP
        $BREW bundle --file=$HOME/.Brewfile
    fi

    echo $CYAN"✔︎ Configuring iTerm2"$STOP
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.config/iterm2"
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

    echo $CYAN"✔︎ Configuring Sublime Text"$STOP
    sudo ln -s  "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime
    rm -rf "$HOME/Library/Application Support/Sublime Text 3/Packages/User"
    ln -s $HOME/.config/sublime "$HOME/Library/Application Support/Sublime Text 3/Packages/User"

    echo $CYAN"✔︎ Installing fzf bindings"$STOP
    $(brew --prefix)/opt/fzf/install

elif [ "$OS" = "FreeBSD" ]; then

    $PKG update
    $PKG neovim rvm cowsay fd-find fzf the_silver_searcher bat

fi

echo $CYAN"✔︎ Configuring vim"$STOP
mkdir -p $HOME/.vim/plugged
curl --silent -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
$VIM +PlugClean +PlugInstall +PlugUpdate +qall

echo $CYAN"✔︎ Configuring NeoVim"$STOP
curl --silent -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

