#!/usr/bin/env bash

# Bootstraps both macOS and Linux (Ubuntu).

# shellcheck source=/dev/null
source "$HOME/.config/bash/conf.d/20-colors.sh"

# Some pre-flight checks...
PREREQS=(yadm curl git)
for PREREQ in "${PREREQS[@]}"; do
  command -v "$PREREQ" &>/dev/null || {
    echo "${RED}$PREREQ is not installed! Going to quit now.${STOP}"
    exit 1
  }
done

# Pull in case we're re-running this on a bootstrapped system
yadm pull --force --strategy-option=theirs

# ========== LINUX ==========

if [[ "$(uname -s)" == "Linux" ]]; then
  echo "${CYAN}✔︎ Installing mise as the runtime manager (setting TMPDIR to HOME/tmp; delete later.)${STOP}"
  TMPDIR="$HOME/tmp" curl -fsSL https://mise.run | sh
  export PATH="$HOME/.local/bin:$PATH"
  # shellcheck source=/dev/null
  eval "$(mise activate bash)"
fi

# ========== MACOS ==========

if [[ "$(uname -s)" == "Darwin" ]]; then
  # Need HomeBrew on macOS for all other stuff
  command -v brew &>/dev/null || {
    echo "${RED}HomeBrew is not installed${STOP}! Going to quit now."
    echo "https://docs.brew.sh/Installation"
    exit 2
  }

  # ----------

  echo "${CYAN}✔︎ Installing mise as the runtime manager${STOP}"
  brew install mise
  # shellcheck source=/dev/null
  eval "$(mise activate bash)"

  # ----------

  echo "${CYAN}✔︎ Running setup for macOS${STOP}"
  LINKS_MACOS=(
    # Source;Target;Name
    '/Applications/GitHub Desktop.app/Contents/Resources/app/static/github.sh;/usr/local/bin/github;Github Desktop'
    '/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl;/usr/local/bin/sublime;Sublime Text'
    '/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code;/usr/local/bin/code;VSCode'
  )

  for LINK in "${LINKS_MACOS[@]}"; do
    SOURCE=$(echo "$LINK" | cut -d";" -f1)
    TARGET=$(echo "$LINK" | cut -d";" -f2)
    NAME=$(echo "$LINK" | cut -d";" -f3)

    if [[ ! -e "$SOURCE" ]]; then
      echo "${RED}$NAME is not installed... skipping${STOP}"
      continue
    else
      echo "${GREEN}Symlinking \"$NAME\": $SOURCE 👉 $TARGET${STOP}"
      sudo ln -sf "$SOURCE" "$TARGET"
    fi
  done

  # ----------

  # For Sublime Text, make sure we are pointing to our config
  SUBLIME_PREFS_FOLDER="$HOME/Library/Application Support/Sublime Text/Packages/User"
  echo "${CYAN}✔︎ Configuring Sublime Text${STOP}"
  rm -rf "${SUBLIME_PREFS_FOLDER}.old"
  mv "$SUBLIME_PREFS_FOLDER" "${SUBLIME_PREFS_FOLDER}.old"
  ln -s "$HOME/.config/sublime" "$SUBLIME_PREFS_FOLDER"
  rm -rf "${SUBLIME_PREFS_FOLDER}.old"
  echo "${GREEN}! Done but you need to start it and install Package Control!${STOP}"
  echo "${GREEN}Removing 'subl' symlink if it exists. It's annoying...${STOP}"
  sudo rm /usr/local/bin/subl >>/dev/null 2>&1

  # ----------

  # Useful Reference: https://macos-defaults.com

  # Set the screenshot format to be JPEG instead of PNG
  defaults write com.apple.screencapture type jpeg
  killall SystemUIServer

  # Finder > Preferences > Advanced
  # When searching, search the current folder and not the entire Mac ffs...
  defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
fi

# ========== GENERAL STUFF ==========

# Configure yadm
echo "${CYAN}✔︎ yadm stuff"
yadm config yadm.cipher openssl
if [[ -f "$HOME/.config/yadm/encrypt" ]]; then
  echo "${YELLOW}👉 Make sure you run 'yadm decrypt' for encrypted files!"
fi

# Install mise stuff
echo "${CYAN}✔︎ Installing mise runtimes...${STOP}"
mise install

# echo "${YELLOW}Running 'ipd' to install platform dependencies...${STOP}"
# "$HOME/.bin/ipd"
# echo "${GREEN}Done${STOP}"
