#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$HOME/.bash_colors"

# Check for pipx
command -v pipx &> /dev/null || {
    echo "${RED}Could not find pipx. Stopping.${STOP}"
    exit
}

OUTPUT_FILE="$HOME/.platform-dependencies/pipx"

# Make an empty output file
# `truncate` not found on fucking macOS
echo "" > "$OUTPUT_FILE"

# shellcheck source=/dev/null
source "$HOME/.bin/platform-versions"

# Finally write dependencies
echo "Writing ${CYAN}${OUTPUT_FILE}${STOP}"
DEPENDENCIES="$(pipx list | grep package | awk '{print $2}')"
echo "$DEPENDENCIES" > "$OUTPUT_FILE"
echo "Done"
