#!/bin/bash

# YUGE WIP.
# Assume that npm is installed

source "$HOME/.bash_colors"

NODE_VERSION="$(node --version)"
OUTPUT_FILE="$HOME/.platform-dependencies/node-$NODE_VERSION"

echo "Writing ${CYAN}${OUTPUT_FILE}${STOP}"
truncate -s0 "$OUTPUT_FILE"

DEPENDENCIES="$(npm list -g --depth 0 --parseable | grep node_modules)"
IFS=$'\n' && for DEP in $DEPENDENCIES; do
    PACKAGE="$(basename "$DEP")"
    VERSION="$(cat $DEP/package.json | grep \"version\" | cut -d\" -f4)"

    echo "${PACKAGE}@${VERSION}" >> "$OUTPUT_FILE"
done

echo "Done"
