#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$HOME/.bash_colors"

# Check if pyenv is managing things
if [[ -z "$PYENV_ROOT" ]]; then
    echo "${RED}Pyenv is not managing Python. Stopping.${STOP}"
    exit
fi

PYTHON_VERSION="$(python --version | cut -d' ' -f2)"
OUTPUT_FILE="$HOME/.platform-dependencies/python-$PYTHON_VERSION"

# Check for pip
command -v pip &> /dev/null || {
    echo "${RED}Could not find pip. Stopping.${STOP}"
    exit
}

# Make an empty output file
# `truncate` not found on fucking macOS
echo "" > "$OUTPUT_FILE"

# Finally write dependencies
echo "Writing ${CYAN}${OUTPUT_FILE}${STOP}"
DEPENDENCIES="$(pip freeze)"
echo "$DEPENDENCIES" > "$OUTPUT_FILE"
echo "Done"
