#!/bin/bash

# shellcheck source=/dev/null
source "$HOME/.bash_colors"

# Check if NVM is managing node versions
if [[ -z "$NVM_BIN" ]]; then
    echo "${RED}NVM is not managing Node. Stopping.${STOP}"
    exit
fi

NODE_VERSION="$(node --version)"
OUTPUT_FILE="$HOME/.platform-dependencies/node-$NODE_VERSION"

echo "Writing ${CYAN}${OUTPUT_FILE}${STOP}"

# `truncate` not found on fucking macOS
echo "" > "$OUTPUT_FILE"

PACKAGE_PATHS="$(npm list -g --depth 0 --parseable 2> /dev/null | grep node_modules)"
IFS=$'\n' && for PACKAGE_PATH in $PACKAGE_PATHS; do
    PACKAGE="$(basename "$PACKAGE_PATH")"

    # Weirdness with this 🤷‍♂️ Not capturing package versions.
    # VERSION="$(grep \"version\" "$PACKAGE_PATH"/package.json | cut -d\" -f4)"
    # echo "${PACKAGE}@${VERSION}" >> "$OUTPUT_FILE"

    echo "${PACKAGE}" >> "$OUTPUT_FILE"
done

echo "Done"
