#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$HOME/.config/bash/conf.d/20-colors.sh"

# ----------

MAJOR_MACOS_VERSION=$(sw_vers -productVersion | cut -d"." -f1)
# MINOR_MACOS_VERSION=$(sw_vers -productVersion | cut -d"." -f2)
MACOS_VERSION="${MAJOR_MACOS_VERSION}"
# MACOS_VERSION="${MAJOR_MACOS_VERSION}.${MINOR_MACOS_VERSION}"

# ----------

OUTPUT_FILE="${HOME}/.platform-dependencies/macos-${MACOS_VERSION}"
OUTPUT_FILE_BROAD="${HOME}/.platform-dependencies/macos"

# ----------

echo "${YELLOW}Backing up Brewfile to ${OUTPUT_FILE}${STOP}"
echo "${YELLOW}Backing up Brewfile to ${OUTPUT_FILE_BROAD}${STOP}"

brew bundle dump \
  --file="${HOME}/.platform-dependencies/macos-${MACOS_VERSION}" \
  --force

cp "$OUTPUT_FILE" "$OUTPUT_FILE_BROAD"
