#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$HOME/.config/bash/colors"

# shellcheck source=/dev/null
source "$HOME/.bin/platform-versions"

OUTPUT_FILE="${HOME}/.platform-dependencies/macos-${MACOS_VERSION}"
OUTPUT_FILE_BROAD="${HOME}/.platform-dependencies/macos"

echo "${CYAN}✔︎  Backing up Brewfile to ${OUTPUT_FILE}${STOP}"
echo "${CYAN}✔︎  Backing up Brewfile to ${OUTPUT_FILE_BROAD}${STOP}"

brew bundle dump \
  --file="${HOME}/.platform-dependencies/macos-${MACOS_VERSION}" \
  --force

cp "$OUTPUT_FILE" "$OUTPUT_FILE_BROAD"
echo "Done"
