#!/bin/bash

# shellcheck source=/dev/null
source "$HOME/.bash_colors"

command -v brew >/dev/null 2>&1 || {
    echo "${RED}Homebrew is not installed.${STOP}"
    exit
}

echo "${CYAN}✔ Backing up${STOP}"
pushd "$HOME" &> /dev/null || exit
rm "$HOME/Brewfile"
brew bundle dump
popd &> /dev/null || exit

echo "${CYAN}✔ Cleaning up${STOP}"
brew cleanup

echo "${CYAN}✔ Updating recipes${STOP}"
brew update

echo "${CYAN}✔ Upgrading packages${STOP}"
brew upgrade
