#!/bin/bash

# Enterprise Engine white noise generator :D Need "sox" on OS X
# http://goo.gl/x1Ow6k
export ENGAGE_PLAY_COMMAND="play -n -c1 synth whitenoise band -n 100 20 band -n 50 20 gain +25 fade h 1 864000 1"
if [[ $(uname) == "Darwin" ]]; then
    alias engage='say -v alex Engage && $ENGAGE_PLAY_COMMAND'
elif [[ $(uname) == "Linux" ]]; then
    alias engage='$ENGAGE_PLAY_COMMAND'
fi

