#!/usr/bin/env bash

# When I screw up and my knowledge of git fails me

TRACKED_FILES=$(yadm list)

IFS=$'\n'; for FILE in $TRACKED_FILES; do
    echo "Removing $FILE"
    rm -rf "$FILE"
done

echo "Removing yadm folder"
rm -rf "$HOME/.yadm"

echo "Cloning remote"
yadm clone "git@github.com:afreeorange/dotfiles.git"
