#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=/dev/null
source "$HOME/.config/bash/colors"

PLATFORM_DEPENDENCIES_ROOT="$HOME/.platform-dependencies"
IFS=$'\n'

function install_node() {
  command -v node >>/dev/null 2>&1 || {
    echo "${RED}Could not find Node!${STOP}"
    exit 1
  }

  MAJOR_NODE_VERSION=$(node -e "console.log(process.versions.node.split('.')[0]);")
  MINOR_NODE_VERSION=$(node -e "console.log(process.versions.node.split('.')[1]);")
  NODE_VERSION="${MAJOR_NODE_VERSION}.${MINOR_NODE_VERSION}"

  echo "${YELLOW}→ Node${STOP} ${CYAN}${NODE_VERSION}${STOP}"

  # Install from the specific version if possible. If not use the broad version.
  local DEPS_FILE_SPECIFIC="$PLATFORM_DEPENDENCIES_ROOT/node-$NODE_VERSION"
  local DEPS_FILE_BROAD="$PLATFORM_DEPENDENCIES_ROOT/node"
  local DEPS_FILE="$DEPS_FILE_SPECIFIC"

  if [[ ! -e "$DEPS_FILE" ]]; then
    echo "${RED}Could not find Node dependencies file for ${NODE_VERSION}${STOP}"
    echo "${YELLOW}Trying $DEPS_FILE_BROAD${STOP}"
    DEPS_FILE="$DEPS_FILE_BROAD"
  fi

  # shellcheck disable=SC2046
  npm i -g $(cat "$DEPS_FILE")
  echo "${GREEN}✓ Done${STOP}"
}

function install_python() {
  command -v python >>/dev/null 2>&1 || {
    echo "${RED}Could not find Python!${STOP}"
    exit 1
  }

  echo "${YELLOW}→ Python${STOP} ${CYAN}${PYTHON_VERSION}${STOP}"
  local DEPS_FILE_SPECIFIC="$PLATFORM_DEPENDENCIES_ROOT/python-$PYTHON_VERSION"
  local DEPS_FILE_BROAD="$PLATFORM_DEPENDENCIES_ROOT/python"
  local DEPS_FILE="$DEPS_FILE_SPECIFIC"

  if [[ ! -e "$DEPS_FILE" ]]; then
    echo "${RED}Could not find Python dependencies file for ${PYTHON_VERSION}${STOP}"
    echo "${YELLOW}Trying $DEPS_FILE_BROAD${STOP}"
    DEPS_FILE="$DEPS_FILE_BROAD"
  fi

  # shellcheck disable=SC2046
  pip install $(cat "$DEPS_FILE")
  echo "${GREEN}✓ Done${STOP}"
}

function install_homebrew() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    command -v brew >>/dev/null 2>&1 || {
      echo "${RED}Could not find HomeBrew!${STOP}"
      exit 1
    }

    MAJOR_MACOS_VERSION=$(sw_vers -productVersion | cut -d"." -f1)
    MINOR_MACOS_VERSION=$(sw_vers -productVersion | cut -d"." -f2)
    MACOS_VERSION="${MAJOR_MACOS_VERSION}.${MINOR_MACOS_VERSION}"

    echo "${YELLOW}→ Homebrew - macOS ${MACOS_VERSION}${STOP}"

    brew bundle --file="${HOME}/.platform-dependencies/macos-${MACOS_VERSION}"
    echo "${GREEN}✓ Done${STOP}"
  else
    echo "${RED}ⅹ Not macOS. Quitting.${STOP}"
  fi
}

if [[ "$1" == "node" ]]; then
  install_node
elif [[ "$1" == "python" ]]; then
  install_python
elif [[ "$1" == "brew" ]]; then
  install_homebrew
elif [[ -z "$1" ]]; then
  install_node
  install_python
  install_homebrew
fi
