#!/bin/bash

if [[ "$(uname -s)" == "Darwin" ]]; then
    ln -sf "/Applications/VSCodium.app/Contents/Resources/app/bin/code" "/usr/local/bin/code"
    ln -sf "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" "/usr/local/bin/sublime"
fi
