#!/usr/bin/env bash

MAJOR_NODE_VERSION=$(node -e "console.log(process.versions.node.split('.')[0]);")
MINOR_NODE_VERSION=$(node -e "console.log(process.versions.node.split('.')[1]);")
export NODE_VERSION="${MAJOR_NODE_VERSION}.${MINOR_NODE_VERSION}"

MAJOR_MACOS_VERSION=$(sw_vers -productVersion | cut -d"." -f1)
MINOR_MACOS_VERSION=$(sw_vers -productVersion | cut -d"." -f2)
export MACOS_VERSION="${MAJOR_MACOS_VERSION}.${MINOR_MACOS_VERSION}"

MAJOR_PYTHON_VERSION=$(python -c "import sys; print(sys.version_info.major)")
MINOR_PYTHON_VERSION=$(python -c "import sys; print(sys.version_info.minor)")
export PYTHON_VERSION="${MAJOR_PYTHON_VERSION}.${MINOR_PYTHON_VERSION}"
