#!/usr/bin/env bash

# Most of this is just symlinking, except for Sublime.

# shellcheck source=/dev/null
source "$HOME/.bash_colors"

LINKS_MACOS=(
    # Source;Target;Name
    '/Applications/GitHub Desktop.app/Contents/Resources/app/static/github.sh;/usr/local/bin/github;Github Desktop'
    '/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl;/usr/local/bin/sublime;Sublime Text'
    '/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code;/usr/local/bin/code;VSCode'
)

if [[ "$(uname -s)" == "Darwin" ]]; then
    for LINK in "${LINKS_MACOS[@]}"; do
        SOURCE=$(echo "$LINK" | cut -d";" -f1)
        TARGET=$(echo "$LINK" | cut -d";" -f2)
        NAME=$(echo "$LINK" | cut -d";" -f3)

        if [[ ! -e "$SOURCE" ]]; then
            echo "${RED}$NAME is not installed... skipping${STOP}"
            continue
        else
            echo "${GREEN}Symlinking \"$NAME\": $SOURCE 👉 $TARGET${STOP}"
            ln -sf "$SOURCE" "$TARGET"
        fi
    done

    # For Sublime Text, make sure we are pointing to our config
    SUBLIME_PREFS_FOLDER="$HOME/Library/Application Support/Sublime Text 3/Packages/User"
    echo "${CYAN}✔︎ Configuring Sublime Text${STOP}"
    rm -rf "${SUBLIME_PREFS_FOLDER}.old"
    mv "$SUBLIME_PREFS_FOLDER" "${SUBLIME_PREFS_FOLDER}.old"
    ln -s "$HOME/.config/sublime" "$SUBLIME_PREFS_FOLDER"
    rm -rf "${SUBLIME_PREFS_FOLDER}.old"
    echo "${GREEN}! Done but you need to start it and install Package Control!${STOP}"

    # Neovim
    echo "${CYAN}✔︎ Configuring Neovim${STOP}"
    curl    --silent \
            --create-dirs \
            -fLo "$HOME/.local/share/nvim/site/autoload/plug.vim" \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    $(which nvim) +PlugClean +PlugInstall +PlugUpdate +qall

    # Deno
    command -v deno || {
        curl -fsSL https://deno.land/x/install/install.sh | sh
    }

    # iTerm2
    echo "${GREEN}! Remember to set up iTerm2 in its preferences!${STOP}"
fi

