#!/bin/bash

# Update Dot Files
# Pull and push changes to my dotfiles

IFS=$'\n'

cd "$HOME"
source "$HOME/.bash_colors"
source "$HOME/.bash_excuses"

OS=$(uname -s)

# TODO: Parse shortopts later but for now
#   adding "b" backs up Brewfiles on macOS
#   adding "d" backs up platform dependencies on all OSes
EXTRA_BACKUP_OPTION=$1

if [[ "$EXTRA_BACKUP_OPTION" == "b" && "$OS" == "Darwin" ]]; then
    echo "${CYAN}✔︎  Backing up Brewfile${STOP}"
    brew bundle dump --file=~/.Brewfile --force
fi

if [[ "$EXTRA_BACKUP_OPTION" == "d" ]]; then
    echo "${CYAN}✔︎  Backing up dependencies${STOP}"

    echo "${YELLOW}+  Node${STOP}"
    "$HOME/.bin/backup-node"

    echo "${YELLOW}+  Python${STOP}"
    "$HOME/.bin/backup-python"

    # TODO: Only add paths output by the scripts above
    yadm add -f "$HOME/.platform-dependencies/*"
fi

echo "${CYAN}✔︎  Attempting pull from Github${STOP}"
yadm pull origin master --quiet
CHANGED_FILES=($(yadm diff --name-status HEAD~1 HEAD))
echo "${GREEN}>  ${#CHANGED_FILES[@]} file(s) have changed since last commit"
for FILE in "${CHANGED_FILES[@]}"; do
    echo "${GREEN}${FILE}${STOP}"
done

echo "${CYAN}✔︎  Collecting any changed or deleted files${STOP}"
FILES=($(yadm status -uno --porcelain | cut -c4- | sed s/\"//g))
if [[ "${#FILES[@]}" -eq 0 ]]; then
    echo "${GREEN}🤷‍♀️ Looks like nothing's changed${STOP}"
    exit 1
fi

for FILE in "${FILES[@]}"; do
    echo "${GREEN}>  ${#FILES[@]} files have changed"
    echo "${GREEN}+  Adding $HOME/$FILE${STOP}"
    yadm add "$HOME/$FILE"
done

echo "${CYAN}✔︎  Committing${STOP}"
yadm commit --quiet --message "$(random_excuse)"

echo "${CYAN}✔︎  Attempting push to Github${STOP}"
yadm push origin master --quiet

