#!/bin/bash

# Update Dot Files
# Pull and push changes to my dotfiles

IFS=$'\n'

cd "$HOME" || return
# shellcheck source=/dev/null
source "$HOME/.bash_colors"
# shellcheck source=/dev/null
source "$HOME/.bash_excuses"

OS=$(uname -s)

# TODO: Parse shortopts later but for now
#   adding "b" backs up Brewfiles on macOS
#   adding "d" backs up platform dependencies on all OSes
EXTRA_BACKUP_OPTION=$1

if [[ "$EXTRA_BACKUP_OPTION" == "b" && "$OS" == "Darwin" ]]; then
    echo "${CYAN}✔︎  Backing up Brewfile${STOP}"
    brew bundle dump --file=~/.Brewfile --force
fi

if [[ "$EXTRA_BACKUP_OPTION" == "d" ]]; then
    echo "${CYAN}✔︎  Backing up dependencies${STOP}"

    echo "${YELLOW}+  Node${STOP}"
    "$HOME/.bin/backup-node"

    echo "${YELLOW}+  Python${STOP}"
    "$HOME/.bin/backup-python"

    # TODO: Only add paths output by the scripts above
    yadm add -f "$HOME/.platform-dependencies/*"
fi

echo "${CYAN}✔︎  Attempting pull from Github${STOP}"
yadm pull origin master --quiet
CHANGED_FILES=()
while IFS='' read -r line; do CHANGED_FILES+=("$line"); done < <(yadm diff --name-status HEAD~1 HEAD)

if [[ "${#CHANGED_FILES[@]}" -eq 0 ]]; then
    echo "${GRAY}>  Nothing has changed since the last commit${STOP}"
elif [[ "${#CHANGED_FILES[@]}" -eq 1 ]]; then
    echo "${GRAY}>  Just one file changed${STOP} some place else"
else
    echo "${GRAY}>  ${#CHANGED_FILES[@]} files have changed since last commit"
fi

for FILE in "${CHANGED_FILES[@]}"; do
    echo "${GRAY}${FILE}${STOP}"
done


echo "${CYAN}✔︎  Collecting any new changed or deleted files${STOP}"
FILES=()
while IFS='' read -r line; do FILES+=("$line"); done < <(yadm status -uno --porcelain | cut -c4- | sed s/\"//g)

if [[ "${#FILES[@]}" -eq 0 ]]; then
    echo "${GRAY}🤷‍♀️ Looks like there's nothing new to push${STOP}"
    exit 1
elif [[ "${#FILES[@]}" -eq 1 ]]; then
    echo "${GREEN}>  Just one file has changed${STOP}"
else
    echo "${GREEN}>  ${#FILES[@]} files have changed"
fi

for FILE in "${FILES[@]}"; do
    echo "${GREEN}+  Adding $HOME/$FILE${STOP}"
    yadm add "$HOME/$FILE"
done

echo "${CYAN}✔︎  Committing${STOP}"
yadm commit --quiet --message "$(random_excuse)"

echo "${CYAN}✔︎  Attempting push to Github${STOP}"
yadm push origin master --quiet

