#!/bin/bash

# Helps me maintain a quick log of things I do at work.
# TODO:
#   - Delete

# Trailing slash!
LOG_FOLDER="$HOME/Dropbox/Work/"
LOG_FILE_PREFIX="worklog"
LOG_FILE="$LOG_FOLDER""$LOG_FILE_PREFIX-$(date "+%F--%b-%a").md"
FILE_TO_EDIT=$LOG_FILE

# Note: The pipes need a new version of `sed`
# TODO: https://stackoverflow.com/a/23357277
IFS=$'\n'
LOGS=($(
    find "$LOG_FOLDER" -type f -iname "$LOG_FILE_PREFIX*" |
        tail -r |
        sed "s|$LOG_FOLDER"/"||" |
        sort
))
unset IFS

# Create a new log for the day if it doesn't exist
if [[ "$#" == 0 ]]; then
    if [[ ! -f "$LOG_FILE" ]]; then
        echo "Will make $LOG_FILE"
        touch "$LOG_FILE"

        cat <<EOF >"$LOG_FILE"
$(date "+%a, %b %d %Y")
----------------


EOF
    fi

# Get me the last log. Useful during standup.
elif [[ "$1" == "-1" ]]; then
    LENGTH=${#LOGS[@]}
    FILE_TO_EDIT="$LOG_FOLDER""${LOGS[$((LENGTH - 2))]}"

# List all the logs
elif [[ "$1" == "l" ]]; then
    COUNTER=0

    for LOG in "${LOGS[@]}"; do
        echo "$(printf "% 4d.\n" $COUNTER)" "$LOG"
        COUNTER=$((COUNTER + 1))
    done

    exit 0

# Decent search with ye olde grep
elif [[ "$1" == "s" ]]; then
    if [[ -z "$2" ]]; then
        echo "Must provide search term"
        exit 1
    fi

    grep -Hin "$2" $LOG_FOLDER/

    exit 0

# Let me pick a log
else
    if [[ "$1" -gt "${#LOGS[@]}" ]]; then
        echo "Why are you like this? That index does not exist."
        exit 1
    fi

    FILE_TO_EDIT="$LOG_FOLDER""${LOGS[$1]}"
fi

$EDITOR "$FILE_TO_EDIT"

