#!/bin/bash

source_if_exists() {
    # shellcheck source=/dev/null
    [[ -e "$1" ]] && source "$1"
}

warn() {
    echo "$RED""❕$1""$STOP"
}

for FILE in "$BASHRC_D"/conf.d/[0-9][0-9]*.sh; do
    # shellcheck source=/dev/null
    [[ -r $FILE ]] && source "$FILE"
done
unset FILE

